theme: jekyll-theme-minimal
title: Joseph Roberts – Ironworker to Innovator
description: Blending field grit with software finesse to modernize construction workflows.
code_review_video: "https://youtu.be/KQWZkkFlBgY"


